allow-lan: true
bind-address: '*'
cfw-bypass:
- qq.com
- music.163.com
- '*.music.126.net'
- localhost
- 127.*
- 10.*
- 172.16.*
- 172.17.*
- 172.18.*
- 172.19.*
- 172.20.*
- 172.21.*
- 172.22.*
- 172.23.*
- 172.24.*
- 172.25.*
- 172.26.*
- 172.27.*
- 172.28.*
- 172.29.*
- 172.30.*
- 172.31.*
- 192.168.*
- <local>
cfw-latency-timeout: 5000
ipv6: false
log-level: info
mode: Rule
proxies:
- alpn:
  - h2
  - http/1.1
  name: JP_ORACLE_TROJAN
  password: wjswkwssyr5188
  port: 443
  server: trj.wan9.top
  type: trojan
- alpn:
  - h2
  - http/1.1
  name: HK_ALY_trojan
  password: wjswkwssyr5188
  port: 443
  server: tr.wan9.top
  type: trojan
- alpn:
    - h2
    - http/1.1
  name: VMISS_LA_trojan
  password: wjswkwssyr5188
  port: 443
  server: tru.wan9.top
  type: trojan
proxy-groups:
- interval: 300
  name: "\u81EA\u52A8\u9009\u62E9\u5FEB\u901F\u8282\u70B9"
  proxies:
  - JP_ORACLE_TROJAN
  - HK_ALY_trojan
  - VMISS_LA_trojan
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: PROXY
  proxies:
  - "\u81EA\u52A8\u9009\u62E9\u5FEB\u901F\u8282\u70B9"
  - JP_ORACLE_TROJAN
  - HK_ALY_trojan
  - VMISS_LA_trojan
  type: select
- name: Final
  proxies:
  - DIRECT
  - PROXY
  type: select
- name: Apple
  proxies:
  - DIRECT
  - PROXY
  type: select
- name: GlobalMedia
  proxies:
  - PROXY
  - JP_ORACLE_TROJAN
  - HK_ALY_trojan
  - VMISS_LA_trojan
  type: select
- name: HKMTMedia
  proxies:
  - DIRECT
  - JP_ORACLE_TROJAN
  - HK_ALY_trojan
  - VMISS_LA_trojan
  type: select
redir-port: 0
rule-providers:
  apple:
    behavior: domain
    interval: 86400
    path: ./ruleset/apple.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  cncidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/cncidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
  direct:
    behavior: domain
    interval: 86400
    path: ./ruleset/direct.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
  gfw:
    behavior: domain
    interval: 86400
    path: ./ruleset/gfw.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
  google:
    behavior: domain
    interval: 86400
    path: ./ruleset/google.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
  greatfire:
    behavior: domain
    interval: 86400
    path: ./ruleset/greatfire.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
  icloud:
    behavior: domain
    interval: 86400
    path: ./ruleset/icloud.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
  lancidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/lancidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
  private:
    behavior: domain
    interval: 86400
    path: ./ruleset/private.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
  proxy:
    behavior: domain
    interval: 86400
    path: ./ruleset/proxy.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
  reject:
    behavior: domain
    interval: 86400
    path: ./ruleset/reject.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
  telegramcidr:
    behavior: ipcidr
    interval: 86400
    path: ./ruleset/telegramcidr.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
  tld-not-cn:
    behavior: domain
    interval: 86400
    path: ./ruleset/tld-not-cn.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
rules:
- RULE-SET,applications,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,reject,REJECT
- RULE-SET,icloud,DIRECT
- RULE-SET,apple,DIRECT
- RULE-SET,google,DIRECT
- RULE-SET,proxy,PROXY
- RULE-SET,direct,DIRECT
- RULE-SET,lancidr,DIRECT
- RULE-SET,cncidr,DIRECT
- RULE-SET,telegramcidr,PROXY
- GEOIP,,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
